### ISSUE TITLE
Use balloon dialogs instead browser alerts

### ISSUE THREAD

**Issue by gsag** [cksource/ckeditor-plugin-a11ychecker#225]
Hi guys, I wonder if are you planning change the alerts thrown by the plugin (browser alerts) to balloon dialogs as an enhancement feature.
I checked the opened issues and there's one (#100) with the same proposal. 
I guess it will be a great enhancement for the plugin usability. 
Thanks for listening.

**Comment by mlewand** [comment]
Why creating a new issue instead of commenting / adding a reaction to the former one? :) Generally, yes we're looking for it, however it's not a highest priority for us at the moment. But for sue as we go on, we'll definitely consider it later.

I'll close this one as a duplicate. Feel free to continue the discussion in issue #100.

**Comment by gsag** [comment]
Sorry! It won't happen again. :)
Thanks, by the way I intent to add a reaction there.
